### ISSUE TITLE
Docker remote host with TLS - Error "self signed certificate"

### ISSUE THREAD

**Issue by chrissyheb** [fmartinou/whats-up-docker#125]
Hello,
first of all thanks for this great piece of work. I'm just starting to figure out the possibilities of WUD.
Im running WUD on my QNAP NAS and I am able to get the status of the NAS docker containers into home assistant (running on a separate RasPi). 
I am trying to add a watcher for the docker daemon of the RasPi by following the TLS tutorial (https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket). As $HOST I used only the IP of the RasPi.
Doing this my Portainer (on NAS) is able to connect to the docker daemon on the RasPi by using **TLS with server and client verification**. But when trying to add a watcher to WUD I get the folliwing errors of _self signed certificate_

> 09:45:06.710  INFO whats-up-docker/watcher.docker.remotehomeassistant: Register with configuration {"host":"x.x.x.x","port":2376,"cron":"0 1 * * *","cafile":"/cert/caDocker.crt","keyfile":"/cert/dockerClient.key","certfile":"/cert/dockerClient.crt","socket":"/var/run/docker.sock","watchbydefault":true,"watchall":false,"watchevents":true}
09:45:06.711  INFO whats-up-docker/watcher.docker.remotehomeassistant: Cron scheduled (0 1 * * *)
09:45:07.743  INFO whats-up-docker/watcher.docker.remotehomeassistant: Cron started (0 1 * * *)
09:45:07.786  INFO whats-up-docker/watcher.docker.remotehomeassistant: Listening to docker events
09:45:08.283  WARN whats-up-docker/watcher.docker.remotehomeassistant: Error when trying to get the list of the containers to watch (self signed certificate)
09:45:08.284  INFO whats-up-docker/watcher.docker.remotehomeassistant: Cron finished (0 containers watched, 0 errors, 0 available updates)
09:45:08.341  WARN whats-up-docker/watcher.docker.remotehomeassistant: Unable to listen to Docker events [self signed certificate]

My docker-compose file looks like this:
```
version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV1_DATA/Docker/WhatsUpDocker/cert/:/cert/:ro
    ports:
      - 12000:3000
    environment:
      - WUD_AUTH_BASIC_CHRISSY_USER=XXX
      - WUD_AUTH_BASIC_CHRISSY_HASH=XXX
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_REMOTEHOMEASSISTANT_HOST=x.x.x.x
      - WUD_WATCHER_REMOTEHOMEASSISTANT_PORT=2376
      - WUD_WATCHER_REMOTEHOMEASSISTANT_CAFILE=/cert/caDocker.crt
      - WUD_WATCHER_REMOTEHOMEASSISTANT_CERTFILE=/cert/dockerClient.crt
      - WUD_WATCHER_REMOTEHOMEASSISTANT_KEYFILE=/cert/dockerClient.key
      - WUD_WATCHER_REMOTEHOMEASSISTANT_CRON=0 1 * * *
      - WUD_TRIGGER_MQTT_HOME_URL=mqtt://ip:port
      - WUD_TRIGGER_MQTT_HOME_USER=XXX
      - WUD_TRIGGER_MQTT_HOME_PASSWORD=XXX
```

Has anyone a hint, what to do to make the connection to remote host work with WUD?
Thanks 
Chrissy
