### ISSUE TITLE
Not able to detect the proper tag for Portainer

### ISSUE THREAD

**Issue by mwolter805** [fmartinou/whats-up-docker#135]
Looks like there might be a tag parsing issue, specifically with Portainer, which has a relatively complex tag compared to the other 20+ monitored containers. None of the other containers have this issue.

WUD thinks the latest tag is ```linux-amd64-2.9.3-alpine``` when this is older than the current tag and the latest available tag is actually ```linux-amd64-2.13.1-alpine``` according to https://hub.docker.com/r/portainer/portainer-ce/tags

![Screen Shot 2022-05-15 at 12 02 53 PM](https://user-images.githubusercontent.com/24851651/168489830-42749494-d408-41bd-9e81-fff4ed995d75.jpg)

docker-compose for portainer:
```
services:
  portainer:
    image: portainer/portainer-ce:linux-amd64-2.11.1-alpine
    container_name: portainer
    hostname: portainer
    environment:
      - TZ=America/Los_Angeles
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --no-check-certificate https://127.0.0.1:9443 || exit 1"]
      interval: 1m
      timeout: 10s
      start_period: 10s
      retries: 3
    labels:
      - wud.tag.include=^linux-amd64-\d+\.\d+\.\d+-alpine$$
      - wud.link.template=https://github.com/portainer/portainer/releases
```

docker-compose for wud:
```
services:
  wud:
    image: fmartinou/whats-up-docker:5.17.1
    container_name: wud
    hostname: wud
    ports:
      - 3000:3000
    environment:
      - TZ=America/Los_Angeles
      - WUD_WATCHER_UTILITYLXC_SOCKET=/var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:3000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/fmartinou/whats-up-docker/releases
```

**Comment by fmartinou** [comment]
Hi,

The reason why this is not working out of the box is because the semver part is not at the beginning of the tag string.
You can get around with this by using the label `wud.tag.transform` that allows to define a function to rewrite the tag to a better one.

You can find the [related documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=transform-the-tags-before-performing-the-analysis).

For your issue, it should look like to something like
```yaml
services:
  portainer:
    image: portainer/portainer-ce:linux-amd64-2.11.1-alpine
    labels:
      - wud.tag.include=^linux-amd64-\d+\.\d+\.\d+-alpine$$
      - wud.tag.transform=^linux-amd64-(\d+)\.(\d+)\.(\d+)-alpine$$ => $$1.$$2.$$3
      - wud.link.template=https://github.com/portainer/portainer/releases
```
