### ISSUE TITLE
healthcheck on docker container

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#139]
Any chances you will add this to the next feature? Thanks man...

**Comment by robertalexa** [comment]
Already exists :)

https://fmartinou.github.io/whats-up-docker/#/monitoring/?id=healthcheck

Here is an extract from my `docker-compose.yml` file

```
healthcheck:                                                                           
  test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:30
  interval: 10s                                                                        
  timeout: 10s                                                                         
  retries: 3                                                                           
  start_period: 10s
```

**Comment by ranrinc** [comment]
I'm copying and paste your code.. it doesn't work. I got unhealthy instead. 
the error from portainer `Connecting to localhost:3003 (127.0.0.1:3003) wget: can't connect to remote host (127.0.0.1): Connection refused`

```
    healthcheck:
      test: wget --no-verbose --tries=1 --no-check-certificate  --spider http://localhost:3003
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
```

on wud latest version.
