### ISSUE TITLE
Issues after switching to semver tagging

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#153]
Hi,

after reading your documentation, I decided it was time to switch to semver (I only used `latest `because I was lazy). :)

I have 52 containers on 3 docker instances.

WUD is working good on most of them, it took a while to configure everything, but I'm pretty satisfied now.

The only problem I'm having is that many images don't have an appropriate semver versioning on the repo, in particular these ones, as you can see WUD thinks there's an updated version but in reality there's not:

![image](https://user-images.githubusercontent.com/7027842/181797098-d1a0762c-5369-4e29-99dc-2b5bdd841fe4.png)

Here are the labels I'm using for a couple ot these:

```yaml
  lidarr:
    image: ghcr.io/linuxserver/lidarr:1.0.2
    container_name: lidarr
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
```
```yaml
  tautulli:
    image: ghcr.io/linuxserver/tautulli:2.10.2
    container_name: tautulli
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
```

Any suggestions are more than welcome. Thanks for your work on WUD. :)

**Comment by fmartinou** [comment]
Regarding `lidarr`, it looks like a person did a mistake and pushed a `8.1.2135` instead of a `0.8.1.2135` 😂 
![image](https://user-images.githubusercontent.com/16061231/183118733-53cf98f8-d004-496a-8b6e-7fe098e55caf.png)

What a shame...
Now lidarr semver versions are wrong... until the `9.x`... 😄 

In the meantime, I see no other way than to adjust the regex.

Something like
```
  lidarr:
    image: ghcr.io/linuxserver/lidarr:1.0.2
    container_name: lidarr
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^[0-7]+\.\d+\.\d+$$'
```

**Comment by alexdelprete** [comment]
All the *arr apps have messy semver tagging. :)

Thanks for the lidarr tip, what about whisparr? Why does it think that .9 is an upgrade vs .49? :)

```yaml
  whisparr:
    image: ghcr.io/hotio/whisparr:nightly-0.1.0.49
    container_name: whisparr
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^nightly\-\d+\.\d+\.\d+\.\d+$$'
```

![image](https://user-images.githubusercontent.com/7027842/183121378-3954aa39-0c7d-4157-aa34-5a606d2fee1d.png)

**Comment by fmartinou** [comment]
> Why does it think that .9 is an upgrade vs .49? :)

Because the digits in fourth position are not compliant with the [semver specification](https://semver.org/)
My guess is that these parts of the version are compared as strings.
So the string 9 is greater than the string 49.

The version `0.1.0.49` is not compliant with semver but `0.1.0-49` would be.
(please pay attention to the DASH instead of the DOT).

So regarding semver:
- 0.1.0.9 > 0.1.0.49
- 0.1.0-9 < 0.1.0-49

You can get around this problem using a [wud.tag.transform](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels) label.

I see 2 possible solutions:

### 1. The easiest one is to just drop the last non compliant part
```yaml
  whisparr:
    image: ghcr.io/hotio/whisparr:nightly-0.1.0.49
    container_name: whisparr
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^nightly\-\d+\.\d+\.\d+\.\d+$$'
      - wud.tag.transform=^nightly-(\d+\.\d+\.\d+).*$$ => $$1
```

### 2. The other one is to rewrite the version as a valid semver one (ie nightly-0.1.0.49 must become 0.1.0-49)
```yaml
  whisparr:
    image: ghcr.io/hotio/whisparr:nightly-0.1.0.49
    container_name: whisparr
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^nightly\-\d+\.\d+\.\d+\.\d+$$'
      - wud.tag.transform=^nightly-(\d+\.\d+\.\d+).(\d+)$$ => $$1-$$2
```
