### ISSUE TITLE
Auto Update with portainer

### ISSUE THREAD

**Issue by legolas0802** [fmartinou/whats-up-docker#154]
to create my containers I use a stack of containers for each of them. this way I get multiple docker-compose.yml files placed in various folders. Is there a configuration that sees this situation?

**Comment by fmartinou** [comment]
Hi,

"In theory", you can set up multiple triggers of the same type so you should be able to set one trigger per compose file.

Something like
```yaml

version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    ...
    volumes:
    - /etc/one/docker-compose.yml:/wud/one/docker-compose.yml
    - /etc/two/docker-compose.yml:/wud/two/docker-compose.yml
    - /etc/three/docker-compose.yml:/wud/three/docker-compose.yml
    environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_ONE_FILE=/wud/one/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_TWO_FILE=/wud/two/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_THREE_FILE=/wud/three/docker-compose.yml
```

I haven't testet it myself but it could work 🤞 
Let me know ;)

**Comment by legolas0802** [comment]
i tried the following setup:
```
    volumes:
      - /appdata/wud/:/store
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dev-disk-by-uuid-c3ea17fc-639f-4af1-967a-453f4d0e6b8e/Container/volumes/portainer_data/_data/compose:/wud
    ports:
      - 3000:3000
    environment:
        - PUID=1000
        - PGID=100
        - TZ=Europe/Rome
        - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://172.18.0.14:1883
        - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
        - WUD_TRIGGER_MQTT_MOSQUITTO_USER=mauro
        - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=p4ss3r0tt0.1
        - WUD_TRIGGER_DOCKERCOMPOSE_PLEX=/wud/1/docker-compose.yml
        - WUD_TRIGGER_DOCKERCOMPOSE_PLEX_PRUNE=true
        - WUD_TRIGGER_DOCKERCOMPOSE_ADGUARD=/wud/5/docker-compose.yml
        - WUD_TRIGGER_DOCKERCOMPOSE_ADGUARD_PRUNE=true
        - WUD_TRIGGER_DOCKERCOMPOSE_JACKET_FILE=/wud/8/docker-compose.yml
        - WUD_TRIGGER_DOCKERCOMPOSE_JACKET_PRUNE=true
        - WUD_TRIGGER_DOCKERCOMPOSE_TAUTULLI_FILE=/wud/11/docker-compose.yml
        - WUD_TRIGGER_DOCKERCOMPOSE_TAUTULLI_PRUNE=true
        - WUD_TRIGGER_DOCKERCOMPOSE_HOMEASSISTANT_FILE=/wud/12/docker-compose.yml
        - WUD_TRIGGER_DOCKERCOMPOSE_HOMEASSISTANT_DRYRUn=true
```
of the 7 triggers only 4 are recognized, excluding the mqtt one, the remaining 3 (homeassistant, jacket and tautulli) work correctly. Any idea why he doesn't recognize others?
