### ISSUE TITLE
regex...I hate it...:)

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#159]
Hi @fmartinou, not an issue of WUD, but my ignorance regarding regex.

I have this for tasmoadmin:

```yaml
services:
  tasmoadmin:
    image: ghcr.io/tasmoadmin/tasmoadmin:v2.1.0-beta15
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+-beta\d+$$'
      - 'wud.link.template=https://github.com/tasmoadmin/tasmoadmin/releases/tag/v$${major}.$${minor}.$${patch}-$${prerelease}'
```

The problem is that WUD is telling me there's a new version:

![image](https://user-images.githubusercontent.com/7027842/188641067-43d5165e-625d-4438-83ed-afcadd3e35bd.png)

I tried several things playing with regex101.com but `\d+` seems it should match multiple digits. I don't know how to make it work as it should.
