### ISSUE TITLE
Amazon Public ECR registry support

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#167]
Hi,

For Traefik, I switched the docker hub registry to `public.ecr.aws` in order to bypass the docker hub limits as much as possible. I knew that WUD supported ECR so I thought it was no problem.

```
services:
  traefik:
    image: public.ecr.aws/docker/library/traefik:v2.8.7
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/traefik/traefik/releases/tag/v$${major}.$${minor}.$${patch}'
```

I configured the ECR registry support in my docker-compose, as per docs, but WUD tells me that that registry is not supported.

```
02:02:52.324  WARN whats-up-docker/watcher.docker.docker1: Error when processing (Unsupported Registry unknown) (container=docker1_traefik)
    Error: Unsupported Registry unknown
```

Would it be possible to add support for the amazon public ECR?

Thanks.
