### ISSUE TITLE
Multiple containers, different versions, only one entry in Images tab

### ISSUE THREAD

**Issue by rasmuslp** [fmartinou/whats-up-docker#17]
Hi,

When I run two containers of the same image -- but different version ranges and include regexes -- only one entry shows in the Images tab. I would expect to see different updates available for the two containers. 
NB: This _might_ be the effect of #16 ?

However, what I would really like is a container based view. Which I believe makes sense, now that the include tags (and others) are specified per container.

**Comment by fmartinou** [comment]
Hi,

Definitely a bug :(

The expected behaviour is to get 1 entry for each unique couple `image+tag`.

Let me explain with this simple example:

```yml
version: '3'

services:
    nginx_1:
        image: nginx:1.9-alpine
        labels:
            - 'wud.tag.include=^[0-9]\d*\.[0-9]\d*-alpine$$'

    nginx_2:
        image: nginx:1.10-alpine
        labels:
            - 'wud.tag.include=^[0-9]\d*\.[0-9]\d*-alpine$$'

    nginx_3:
        image: nginx:1.10-alpine
        labels:
            - 'wud.tag.include=^[0-9]\d*\.[0-9]\d*-alpine$$'
```

So 3 nginx instances:
- One 1.9 instance
- Two 1.10 instances

I expect to see 2 entries in the images tab and to get 2 notifications:
- 1.9 update
- 1.10 update

Would it suit you?
