### ISSUE TITLE
[Enhancement] Optional entity_picture

### ISSUE THREAD

**Issue by ioull** [fmartinou/whats-up-docker#194]
Is it possible to have an option to remove the entity_picture in homeassistant device ?
Avant :
![image](https://user-images.githubusercontent.com/6410144/209851213-b34f7068-c4ab-4a9a-b3a2-b45d9c312c64.png)

Apres migration 6.0:
![image](https://user-images.githubusercontent.com/6410144/209851309-e765eb45-b936-4047-9dbf-20ec4e20d8e2.png)

**Comment by fmartinou** [comment]
Hi,

If the entity_picture is not provided, then the sensors in the `device page` are displayed with a generic (ugly) `MQTT` image.
(That's why I added an entity picture)

Most of the cards actually still display the icon **except the entities card** (to my knowledge), which is bad, I agree.

Some possible proposals for you:
- Set the `icon` option on your entities to display the icons
- Use a `template` card to set the `icon` from the attribute of the sensor
- Use another kind of card ([for example a mushroom card](https://github.com/piitaya/lovelace-mushroom))


Below an example to display containers using mushroom update cards
![image](https://user-images.githubusercontent.com/16061231/210170154-123a8421-323f-4ab0-8a66-d017d2529627.png)

Below an example to filter on all available updates using a mushroom template card
![image](https://user-images.githubusercontent.com/16061231/210170090-eabc4914-22a5-497d-b8c8-92adee5fb9cb.png)
```yaml
type: custom:auto-entities
card_param: cards
filter:
  include:
    - device_model: Wud
      state: 'on'
      options:
        type: custom:mushroom-update-card
sort:
  method: friendly_name
show_empty: false
card:
  type: grid
  title: Mises à jour
  columns: 2
  square: false
```
