### ISSUE TITLE
Labels are not processed

### ISSUE THREAD

**Issue by pavolholes** [fmartinou/whats-up-docker#198]
I'm monitoring all containers using the below local watcher:
```
services:
  whatsupdocker:
    environment:
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=true
```

WUD founds a new tag for Frigate container which it is trying to update to tag `cleanup_events-6877432-amd64` which I don't want to because this tag is not working.
 
![image](https://user-images.githubusercontent.com/35877348/210506569-05aadf3a-4270-4ce2-b981-fb3d2c2673df.png)

I've applied below [Labels](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels) to the Frigate compose (in Portainer Stack). I've started with the `wud.tag.include` which didn't help so I've added also the `wud.tag.transform` but that also didn't help:
```
services:
  frigate:
    environment:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.tag.transform=^(\d+\.\d+\.\d+)$$ => $$1
```

... and Frigate got updated again few minutes ago:
```
22:37:50.437  INFO whats-up-docker/trigger.docker.primary: Pull image blakeblackshear/frigate:cleanup_events-6877432-amd64 (container=local_frigate)
22:38:57.621  INFO whats-up-docker/trigger.docker.primary: Image blakeblackshear/frigate:cleanup_events-6877432-amd64 pulled with success (container=local_frigate)
```

The issue is with that tag - it doesn't work and container doesn't start - I get error 400 when I manually try to start the container. Also WUD didn't start the container:
```
22:39:04.595  WARN whats-up-docker/trigger.docker.primary: Error when starting container frigate (container=local_frigate)
``` 

At the end I've added `- wud.watch=false` but Frigate was again updated. It seems to me that the Labels are not read from the container by WUD. But I don’t see any messages in the WUD log in regards to this and I didn’t find a way to change log level to debug in the docs. 

Frigate container:
```
services:
  frigate:
    environment:
      - wud.watch=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.tag.transform=^(\d+\.\d+\.\d+)$$ => $$1
```

How can I troubleshoot this please? May I kindly ask you for advice?
Thank you so much! 🙏

**Comment by jpbaril** [comment]
@pavolholes It's "labels" not "environment" so it must rather be like this:
```
services:
  frigate:
    labels:
      - wud.watch=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.tag.transform=^(\d+\.\d+\.\d+)$$ => $$1
```
