### ISSUE TITLE
Need help for postgres:11-alpine

### ISSUE THREAD

**Issue by Isa-78** [fmartinou/whats-up-docker#215]
Hello @fmartinou , 

I'm running a wiki.js instance with postgres database and wud keeps telling that there's a new update => 15.1-bullseye

I tried `image: docker.io/postgres:11-alpine` as well as `image: /postgres:11-alpine` in my stack but the result is the same. 
Any idea on how to solve this? 

Thanks in advance for your support !

**Comment by fmartinou** [comment]
Hello @Isa-78 ,

You need to provide a regular expression to match only the tag formats you're interested in.

To do it, you need to [add docker labels to your postgres container](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels).

Below 2 examples whether you  want to track major+minor versions or major versions only
```yaml
version: '3'

services:

  postgres_major_and_minor:
    image: postgres:11.18-alpine
    labels:
      - 'wud.tag.include=^\d+\.\d+-alpine$$'

  postgres_major_only:
    image: postgres:11-alpine
    labels:
      - 'wud.tag.include=^\d+-alpine$$'
```
