### ISSUE TITLE
Documentation on IFTTT is inconsistent

### ISSUE THREAD

**Issue by jasongordon** [fmartinou/whats-up-docker#23]
See highlights below.  What is the proper way to configure IFTTT because I cant seem to get it to work.

![wud](https://user-images.githubusercontent.com/2027525/104233978-c40ff980-5420-11eb-8ee8-2a57768e1175.PNG)
```
version: '3'
services:
  wud:
    image: fmartinou/whats-up-docker:3.1.2
    ports:
        - 3001:3000
    volumes:
        - /Users/jgordon/docker/volumes/whats-up-docker:/store
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - WUD_TRIGGER_IFTTT_IFTTT1_KEY=MYKEY_HERE
    labels:
       - 'wud.tag.include=^[0-9]\d*.[0-9]\d*.[0-9]\d*$$'
  ```
