### ISSUE TITLE
Web Ui on a different port

### ISSUE THREAD

**Issue by conors06** [fmartinou/whats-up-docker#240]
When I use WUD on port 3000 it loads but when I use 3002 as my dashboard is on 3000 it doesn't load?
![image](https://user-images.githubusercontent.com/91201753/224504627-a05c74dd-b1e0-41ab-b600-8da7320a579e.png)

**Comment by fmartinou** [comment]
Hi,

There is a mistake In your configuration; you're mapping the port `3002` of your host with the port `3002` of the container whereas `wud` is listening to the port `3000`.

If you want `wud` to be reachable on the port `3002` of your host machine, you have 2 possibilities.

1. Just map the `3002` host port with the `3000` container port
```yaml
services:
  wud:
    ports:
      - 3002:3000
```

2. Or map the `3002` host port with the `3002` container port BUT [configure `wud` to listen to the `3002` port](https://fmartinou.github.io/whats-up-docker/#/configuration/server/?id=set-http-listener-port-to-8080)
```yaml
services:
  wud:
    ports:
      - 3002:3002
    environment:
      - WUD_SERVER_PORT=3002
```
