### ISSUE TITLE
Allow anonymous access to GCR

### ISSUE THREAD

**Issue by bossm8** [fmartinou/whats-up-docker#262]
Hi folks, first of all thank you for this cool project!

I am using [cadvisor](https://github.com/google/cadvisor) which is hosted publicly on google's container registry.
But there is no option like `WUD_REGISTRY_HUB` which enables the registry anonymously. I have now used a workaround like this in my docker-compose which works fine and I am able to check for new versions of the cadvisor image:

```yml
environment:
      WUD_REGISTRY_GCR_CLIENTEMAIL: "testmail@test.com"
      WUD_REGISTRY_GCR_PRIVATEKEY: "test"
```

Perhaps there could also be an option `WUD_REGISTRY_GCR`  or this workaround could be added to the documentation?
