### ISSUE TITLE
lscr username required? 

### ISSUE THREAD

**Issue by Isa-78** [fmartinou/whats-up-docker#291]
Hello @fmartinou 

I'm not sure when it started but the lcsr registry is no longer working as expected. 

I can see this in the log which is not consistent with the documentation:
`15:20:08.786  WARN whats-up-docker/registry: Some registries failed to register (Error when registering component lscr ("username" is required))`

Here's my docker stack: 

```
version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://192.168.x.xx:1883
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER=xxxx
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=xxxxx
      - WUD_TRIGGER_MQTT_MOSQUITTO_TOPIC=wud_portsyno
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_PREFIX=homeassistant
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_REGISTRY_HUB=      
      - WUD_REGISTRY_HUB_LOGIN=xxxxxxx
      - WUD_REGISTRY_HUB_PASSWORD=dckr_xxxxxxxxxxx
      - WUD_REGISTRY_GHCR=
      - WUD_REGISTRY_LSCR_TOKEN=ghp_xxxxxxxxxxxxxx      
      - WUD_WATCHER_1_HOST=192.168.x.xx
      - WUD_WATCHER_1_WATCHALL=true
      - WUD_WATCHER_2_HOST=192.168.x.xx
      - WUD_WATCHER_2_WATCHALL=true
```

Can you please tell me what I'm missing here? 

Thanks
