### ISSUE TITLE
Link to the Registry Page of available update

### ISSUE THREAD

**Issue by rezstje** [fmartinou/whats-up-docker#340]
More of a QOL than an actual feature request.

I think it would be a really great addition if under the update tab of a container there would be a link to the registry page of the image. This way, you could quickly find any extra information like changelogs for said update and decide on whether you want to update your container.

**Comment by fmartinou** [comment]
Hi,

Currently, there is the possibility to [associate a browsable link to the image (`wud.link.template`)](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels).
That's a template which is rendered for both the current running image  and the update candidate found on the remote registry.

For example:
```yaml
version: '3'

services:

  mariadb:
    image: mariadb:10.6.4
    labels:
      - wud.link.template=https://mariadb.com/kb/en/mariadb-$${major}$${minor}$${patch}-changelog
```

Maybe could you leverage this feature to point to the registry page?
