### ISSUE TITLE
Beginners help needed

### ISSUE THREAD

**Issue by filikun** [fmartinou/whats-up-docker#358]
Hey! I'm trying to setup What's up docker. I'm running Portainer with a couple of stacks and got Wud up and running but it mainly finds digests. I have the MQTT and HA integration going and as you can see the installed version is "stable".

1. How do I get the version numbers going? 
2. Do I use the docker or docker compose trigger to auto update?
3. How do I find what versioning number the image is using? Most of my stacks uses latest or stable.
4. Will I be able to use the update sensor in HA to actually trigger the update? 

![image](https://github.com/fmartinou/whats-up-docker/assets/9947929/877bb07b-b680-4e74-b413-21aed43231b5)

Here's my frigate stack.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    network_mode: host
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    .....
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+.*$'
```

Wud stack
```
version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    restart: unless-stopped 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/whatsupdocker:/store
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Stockholm
      - WUD_REGISTRY_HUB_LOGIN=secretuser
      - WUD_REGISTRY_HUB_PASSWORD=secretpassword
      - WUD_REGISTRY_LSCR_TOKEN=secrettoken
      - WUD_REGISTRY_GHCR_TOKEN=secrettoken
      - WUD_TRIGGER_MQTT_{trigger_name}_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_{trigger_name}_URL=mqtt://10.0.50.50:1883
      - WUD_TRIGGER_MQTT_{trigger_name}_HASS_PREFIX=docker      
      - WUD_TRIGGER_MQTT_{trigger_name}_USER=secretuser
      - WUD_TRIGGER_MQTT_{trigger_name}_PASSWORD=secretpassword
    labels:
        - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'   
```

Sorry if these are very basic questions. I've tried going trough the documentation a couple of times and reading some github issues and the Home Assistant forum post but I can't get this right in my head.
