### ISSUE TITLE
docker-compose trigger

### ISSUE THREAD

**Issue by nanhoes** [fmartinou/whats-up-docker#388]
Please help me understand the use of the docker-compose trigger.
I have a git repo of all my compose files on my server structured as `/volume2/docker/{CONTAINER}/docker-compose.yml`
What i would like to do:
- Make a change to my compose file on my remote repo
- Push changes to the repo on my server
- This triggers WUD to do all the things from the docs to the container

Is this how the trigger works? Here is my compose file with the intent to perform the trigger on the WUD compose file:
```
version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=/docker/wud/docker-compose.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume2/docker:/docker
    ports:
      - 3000:3000
    restart: unless-stopped
``` 
I have also tried mounting the compose file itself like this: `/volume2/docker/wud/docker-compose.yml:/docker/wud/docker-compose.yml`
Neither config updates my container on a push to the repo. Is there anything else I need to add if this is possible?
Thanks!

**Comment by utdrmac** [comment]
I'm going to chime in here as a brand new user to WUD, in that I agree with you. The documentation is extremely non-helpful when explaining how to get containers to restart when new images are available. Sure, i got the notifications, but I thought this was supposed to also update the yaml and then restart the container.

**Comment by fmartinou** [comment]
Hi,

The purpose of this trigger is to rewrite the docker-compose.yml file and to recreate the containers that have changed.

The global process is [described in the doc](https://getwud.github.io/wud/#/configuration/triggers/docker-compose/):
![image](https://github.com/user-attachments/assets/6f3120de-6805-415a-9fcb-67e770349590)

If the doc is "extremely non-helpful", please ; help me improve it ;)

**Comment by phinphan20** [comment]
This took a minute to get working.  This is how I got it working and might help someone trying to get this to work. Could be added to the docs for clarification, if it seems helpful

This is all in the WUD docker-compose yaml, nothing is needed in the apps docker-compose yaml
```
environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_app-name_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_app-name_FILE=/app-name/docker-compose.yaml
volumes:
      - /path/to/app/docker-compose.yaml:/app-name/docker-compose.yaml
 ```

I think one of the confusing parts in the example is, what paths go where.  The `volume` path points to where the docker-compose file is on your system and maps it to where you want it in the container.  The `trigger` is pointing to the folder where you mapped it to in the container.

**Comment by JtMotoX** [comment]
I still don't understand the documentation. Is it designed to make changes to my docker-compose.yml file? I don't want it to make changes. If my docker-compose.yml service is defined with `:12-latest`, I simply want it to do a `docker compose pull` and `docker-compose restart` whenever an update is available.  Can it do this?

**Comment by phinphan20** [comment]
From my understanding, that is what this trigger does.  It updates the yaml with the latest version, pulls the new image, stops the container and restarts the container with the new version.  I think it is all or nothing with this trigger, otherwise it is a manual process.

**Comment by JtMotoX** [comment]
So you're saying it will update my docker-compose.yml and replace `:12-latest` with `:12.2` or `latest`?  What I really need is for it to just leave my version tag alone and simply pull it if there is an update available.

When you say "manual process", do you mean I have to manually have to click a button in wud to perform the update? I can't find where I can do this.  I see in the 'Containers' section it shows I have 13 updates available, but I can't find where to "manually" update them.  Or do you mean that I have to manually run docker commands as I have always done?  If so, then how does WUD "keep your containers up-to-date"?

**Comment by phinphan20** [comment]
Correct, this trigger will update the docker-compose.yaml from `:12-latest` to `12.2` or whatever the latest version is.  To my knowledge there is no way to not have it update the yaml.

When I say manual, I mean manually updating the yaml file to the version you want, and then running the CLI commands to pull the new image and update your containers, like you have always done.  This is what I am doing.  I just use the WUD dashboard to see when new versions are available.  I do not want the trigger to automatically update them, so I can view if there are breaking changes first and then update everything manually.  WUD will only keep them up-to-date if you use this trigger.

**Comment by JtMotoX** [comment]
Got it. Thanks for the info. I was hoping this could automatically update specific services that are non-customer-impacting (e.g. autoheal, pulseway, etc..) while giving me the option to "manually" update customer-impacting services by clicking an "update" button in the GUI when I have time to monitor and test after updating.

**Comment by JtMotoX** [comment]
It took about 3 hours to create exactly what I needed.

![Image](https://github.com/user-attachments/assets/84d292a1-d221-45f0-bd82-8dc352c8b98c)

**Comment by amosyuen** [comment]
Hi the docker compose trigger seems broken to me when you have multiple containers or I'm using it completely incorrectly.

All my containers are in docker compose files and I want them updated as part of the trigger.

My config for WUD container:
```yaml
...
    volumes:
      - /home/docker/portainer/compose:/mnt/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_adguard_AUTO=false
      - WUD_TRIGGER_DOCKERCOMPOSE_adguard_FILE=/mnt/portainer/46/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_adguard_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_adguard_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_cloudflared_AUTO=false
      - WUD_TRIGGER_DOCKERCOMPOSE_cloudflared_FILE=/mnt/portainer/17/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_cloudflared_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_cloudflared_PRUNE=true
      ... (There's a docker compose trigger for each container) ...
```

I haven't tested it extensively but it looks to me that any time there is an update to one of the containers, all the docker compose triggers fire and every compose file may get updated. I'm not sure if you do some matching within the compose file to figure out exactly which verison to update, if you do that would be good to document.

I think what I really want is each docker container to have a label like
`'wud.tag.docker_compose_file=/mnt/portainer/46/docker-compose.yaml'`

Then have the trigger determine the file to update based on the label of the container that has a new update.
