### ISSUE TITLE
No updates are detected. What am I doing wrong? 

### ISSUE THREAD

**Issue by wgfilho** [fmartinou/whats-up-docker#393]
Hi!

I'm not getting updates for images that I'm not using "latest" as the TAG. Here's one example, but it's happening to more than that on my system.

I have the following docker compose (omitted irrelevant parts, if you think they're relevant, please let me know and I'll post the whole file):

```
services:
  jackett:
    image: linuxserver/jackett:0.21.2691
    container_name: jackett
    labels:
      - wud.tag.include="^\d+\.\d+\.\d+$$"
```

WUD says that there are no updates for it, and this is what I get when calling containers/b4a0b717059ed678fc5ea741c01cd1331378f3bc808e6c60a4c108cc94ef1198/watch

```
{
    "id": "b4a0b717059ed678fc5ea741c01cd1331378f3bc808e6c60a4c108cc94ef1198",
    "name": "jackett",
    "status": "running",
    "watcher": "local",
    "includeTags": "\"^\\d+\\.\\d+\\.\\d+$\"",
    "excludeTags": null,
    "transformTags": null,
    "linkTemplate": null,
    "displayName": "jackett",
    "displayIcon": "mdi:docker",
    "image": {
        "id": "sha256:ca0d6598412ab1156eca17ac334088ceaa2e255177c9c4438222af4e1cab5d40",
        "registry": {
            "url": "https://registry-1.docker.io/v2",
            "name": "hub"
        },
        "name": "linuxserver/jackett",
        "tag": {
            "value": "0.21.2691",
            "semver": true
        },
        "digest": {
            "watch": false,
            "repo": "sha256:0049fac4ce3055ad503ffde3505f47893603094f8387abe3b5a54e2e3b74cfd7"
        },
        "architecture": "amd64",
        "os": "linux",
        "variant": null,
        "created": "2024-05-25T06:45:28.062Z"
    },
    "updateAvailable": false,
    "updateKind": {
        "kind": "unknown",
        "localValue": null,
        "remoteValue": null,
        "semverDiff": null
    },
    "result": {
        "tag": "0.21.2691"
    }
}
```

But looking at https://hub.docker.com/r/linuxserver/jackett/tags I can see that there are newer tags with the format x.y.z, like 0.21.2850, 0.21.2831, etc, and they're all greater than 0.21.2691.

What am I doing wrong on the configuration?

Thanks!

**Comment by fmartinou** [comment]
Hi,

I found the glitch; this is about quotes on the `wud.tag.include` label in your compose file.

Replace as below and it will work:

```yaml
services:
  jackett:
    image: linuxserver/jackett:0.21.2691
    container_name: jackett
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
```
