### ISSUE TITLE
Feature Request: Connect to remote docker daemon via ssh

### ISSUE THREAD

**Issue by cryptogeek13** [fmartinou/whats-up-docker#416]
Docker supports remote connections via ssh: https://docs.docker.com/engine/security/protect-access/#use-ssh-to-protect-the-docker-daemon-socket

This looks like the most secure and most convenient way to connect to remote daemons, because most people are familiar with ssh and it's a lot easier than setting up secure access over TCP by creating your own CA and creating/signing keys. I also saw people using [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) instead, despite the maintainer explicitly advising against opening the containers port to any public network, but I suppose it's simply way easier and convenience wins over security a lot of times, especially if used in non-production or selfhosted environments.

Looking at the docker documentation, it seems like it's quite easy to use. On the remote side one only has to create a user, add it to the docker group and copy the ssh key into authorized_keys. From WUD point of view one only needs to use any authorized ssh key that's mounted into the container, create a context with user and host and then use that context.

But to be fair I don't know this project enough to estimate the amount of work necessary to implement switching between different contexts.

Anyways, thank you for your work. This project is just great. It helps me a lot keeping track of my containers and updating them in time.

**Comment by fmartinou** [comment]
Hi,

Thanks for the request 👍 

Taking a look at the node.js library I use to connect to the Docker engine, it seems doable:
https://github.com/apocas/docker-modem?tab=readme-ov-file#ssh

I add it to my todo list.

**Comment by MassiPi** [comment]
definitely a +1 for this. http seems a no go for me, managing certificates becomes a nightmare after the first renewal..

**Comment by webysther** [comment]
> Docker supports remote connections via ssh: https://docs.docker.com/engine/security/protect-access/#use-ssh-to-protect-the-docker-daemon-socket
> 
> This looks like the most secure and most convenient way to connect to remote daemons, because most people are familiar with ssh and it's a lot easier than setting up secure access over TCP by creating your own CA and creating/signing keys. I also saw people using [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) instead, despite the maintainer explicitly advising against opening the containers port to any public network, but I suppose it's simply way easier and convenience wins over security a lot of times, especially if used in non-production or selfhosted environments.
> 
> Looking at the docker documentation, it seems like it's quite easy to use. On the remote side one only has to create a user, add it to the docker group and copy the ssh key into authorized_keys. From WUD point of view one only needs to use any authorized ssh key that's mounted into the container, create a context with user and host and then use that context.
> 
> But to be fair I don't know this project enough to estimate the amount of work necessary to implement switching between different contexts.
> 
> Anyways, thank you for your work. This project is just great. It helps me a lot keeping track of my containers and updating them in time.

Use this to be less unsafe:

```yml
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.4
    environment:
      - DISABLE_IPV6=1
      - IMAGES=1
      - CONTAINERS=1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      wud.tag.include: '^\d{1,2}\.\d{1,2}\.\d{8}$$'
      wud.link.template: 'https://hub.docker.com/r/linuxserver/socket-proxy/tags'
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
```

I don't know if WUD allow custom port for socket, if this is allowed you can also create even exposed this container only for this, but never expose on internet or unsafe networks.

This container is read-only, socket read-only, resouce constrained, IPV6 disabled which will reduce the attack surface.

@fmartinou will be nice for the project put what endpoint is consumed over socket to fine grained permission.
