### ISSUE TITLE
[Feature Request] Replace parts of image path to bypass docker registry cache

### ISSUE THREAD

**Issue by Stitch10925** [fmartinou/whats-up-docker#451]
Hey everyone,

I am currently using [docker-registry-cache](https://github.com/lhns/docker-registry-cache) to cache images I am pulling so I don't have to re-download them, and to have a local version in case I would temporarily lose my internet connection.

The problem I am facing, is that none of the image version tracking tools work when a cache sits in-between.

When using Docker Registry Cache an Image path might look something like this:
> localhost:5000/paperlessngx/paperless-ngx:2.12

Here the first part of the path is the url to the local cache, followed by the actual repository path.

I was wondering if a feature/configuration could be added in which you ask WUD to remove a certain text in the path. In my example removing "localhost:5000/" would yield the actual repository path without cache. When this path is used WUD could bypass the cache and check the version from the repository directly.

This would give me the best of both worlds: A cache and a way to check for version updates.

**Comment by fmartinou** [comment]
Hi,

Your request makes sense 👍 .

I see to add an option that makes possible to specify another registry for the lookup than the one used by running container.

**Comment by Stitch10925** [comment]
@fmartinou 

Hey, thank you for the fast reply! 

I'm not sure if adding an alternative registry would be enough? How would that work if you're pulling from multiple registries, for example: Docker Hub and Github Package Repo?

I would think that just removing the part of the path that symbolizes the cache url would be much easier? 

Anyways, I don't know the technicalities of WUD, so I shouldn't interfere with how you're planning on solving the issue. :-)

I'm really excited and grateful that you decided to pick up this request. Much appreciated!

**Comment by Stitch10925** [comment]
I just noticed you already merged a feature branch for it, wow! That was really fast :-D

**Comment by fmartinou** [comment]
> I'm not sure if adding an alternative registry would be enough? How would that work if you're pulling from multiple registries, for example: Docker Hub and Github Package Repo?

This "alternate registry" config will be per container.
That means that you should be able to configure one container to look for updates on Docker Hub and another one to look for updates on Github packages.

```yaml
services:

  paperless:
    image: localhost:5000/paperlessngx/paperless-ngx:2.12
    labels:
      - wud.registry.lookup.url=https://registry-1.docker.io
```

I just made the implementation but I haven't tested it (have to setup a full environment for that 😓 ).

Would you please give it a try?
The image version to use is `fmartinou/whats-up-docker:feature__451_customizable_registry_url`

**Comment by Stitch10925** [comment]
I don't want to be a pain, but isn't that making it more difficult than it needs to be? Your solution would require me to add labels to all of my compose files/containers in order for it to work. 

Wouldn't it be more user-friendly to just be able to tell WUD to remove the cache server part of the image paths?

Some examples of image paths (with cache) are: 
- localhost:5000/ghcr.io/dgtlmoon/changedetection.io:0.46.04 (GitHub Repo)
- localhost:5000/ckulka/baikal:0.9.5-nginx-php8.2 (Docker Hub)

As you can see, removing "localhost:5000/" leaves you with the correct repository path without having to add any labels to any compose files/containers. Being able to "set and forget" this configuration would be much easier and faster. 

I don't know how other image caches work, so maybe that's why you choose to take this approach? Either way, I'm definitely willing to test it out since this is a feature I'm really interested in. 

I will test it as soon as possible, but I'm not sure if I'll get to it this weekend.

**Comment by Stitch10925** [comment]
I did some quick research into pull-through caching for Docker. Most solutions I found seem to use the [Docker Mirror](https://docs.docker.com/docker-hub/mirror/) setting to put themselves in-between the online repository and the node requesting the image. 

I seem to have picked a solution that makes use of adding the URL to the image path in order for the requested image to reach the proxy. I'm wondering if adding the cache I'm using to the Docker Mirror section would work as well, and if so, if WUD can check for updates through it. 

I will have to test that as well.

**Comment by fmartinou** [comment]
> Wouldn't it be more user-friendly to just be able to tell WUD to remove the cache server part of the image paths?

Maybe both options can be added?
- A global option at the watch level to cover the case where the registry cache prefixes image paths with the FQDN of the upstream registry
- Labels at container level to fine-tune and cover all other _more or less weird_ use cases 😁 ?

**Comment by Stitch10925** [comment]
That sounds like a good plan :) Awesome!

**Comment by EdwinKM** [comment]
As Docker Hub continues to impose more restrictions on pull limits, this ticket caught my attention. The solution proposed by Stitch10925 seems solid. Simply allow us to configure our own registry (or multiple registries) in a list (e.g., localhost:5000, registry.home.mydomain.com) and internally strip matching strings accordingly.

**Comment by EdwinKM** [comment]
I’ve spent some time on this issue.

The Docker Registry image can be set up as a [pull-through cache](https://docs.docker.com/docker-hub/image-library/mirror/#run-a-registry-as-a-pull-through-cache). But this only works for one upstream [registry](https://github.com/rpardini/docker-registry-proxy?tab=readme-ov-file#why-not-use-dockers-own-registry-which-has-a-mirror-feature).

The solution from Stitch10925 is probably not feasible. The Compose file starts Docker. WUD can, of course, parse the image path to determine the version, but this still doesn’t work for Docker.

Other solutions include [docker-registry-proxy](https://github.com/rpardini/docker-registry-proxy), but then you need to be able to modify http-proxy in daemon.json and/or install certificates. My Docker host is an appliance, and this is not possible. So, I use a valid domain with a wildcard certificate and now start a container per registry. It's not ideal, but it seems to work. I even share storage between all containers (seems harmless).

I think the label solution is elegant enough.

Validated with image "fmartinou/whats-up-docker:feature__451_customizable_registry_url".
Does not work with version "getwud/wud:8.0.1".

Initial:
`image: docker.io/gitea/gitea:1.22.2-rootless`
Changed to:
`image: registry-dockerhub.home.mydomain.com/gitea/gitea:1.22.2-rootless`
`Label: wud.registry.lookup.url=https://registry-1.docker.io`
Result in WUD:
`Registry name = hub, Registry url = https://registry-1.docker.io/v2, https://registry-1.docker.io (lookup)`

Initial:
`image: ghcr.io/alexta69/metube:2025-03-06`
Changed to:
`image: registry-github.home.mydomain.com/alexta69/metube:2025-03-06`
`Label: wud.registry.lookup.url=https://ghcr.io`
Results in WUD:
`Registry name = ghcr, Registry url = https://registry-github.home.mydomain.com/v2, https://ghcr.io (lookup)`

Initial:
`image: lscr.io/linuxserver/sabnzbd:4.4.1`
Changed to:
`image: registry-linuxserver.home.mydomain.com/linuxserver/sabnzbd:4.4.1`
`Label: wud.registry.lookup.url=https://lscr.io`
Results in WUD:
`Registry name = unknown, Registry url = registry-linuxserver.home.mydomain.com, https://lscr.io (lookup)`

So, it seems to work for the most part, except for LSCR?





```
services:

  registry-private:
    image: registry:2.8.2
    pull_policy: missing
    container_name: registry-private
    hostname: registry-private
    volumes:
      - /mnt/tank/container_data/registry_images:/var/lib/registry
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tank/container_data/registry_auth:/auth:ro
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+?$$
      - traefik.enable=true
      - traefik.http.routers.registry-private-https.rule=Host(`registry-private.home.mydomain.com`)
      - traefik.http.routers.registry-private-https.entrypoints=websecure
      - traefik.http.routers.registry-private-https.tls=true
      - traefik.http.routers.registry-private-https.tls.certresolver=letsencryptresolver
      - traefik.http.services.registry-private.loadbalancer.server.port=5000
    environment:
      - TZ=Europe/Amsterdam
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    restart: no
    networks:
      - traefik-net

  registry-dockerhub:
    image: registry:2.8.2
    container_name: registry-dockerhub
    hostname: registry-dockerhub
    volumes:
      - /mnt/tank/container_data/registry_images:/var/lib/registry
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry-dockerhub-https.rule=Host(`registry-dockerhub.home.mydomain.com`)
      - traefik.http.routers.registry-dockerhub-https.entrypoints=websecure
      - traefik.http.routers.registry-dockerhub-https.tls=true
      - traefik.http.routers.registry-dockerhub-https.tls.certresolver=letsencryptresolver
      - traefik.http.services.registry-dockerhub.loadbalancer.server.port=5000
    environment:
      - TZ=Europe/Amsterdam
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    restart: no
    networks:
      - traefik-net
      
  registry-github:
    image: registry:2.8.2
    container_name: registry-github
    hostname: registry-github
    volumes:
      - /mnt/tank/container_data/registry_images:/var/lib/registry
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry-github-https.rule=Host(`registry-github.home.mydomain.com`)
      - traefik.http.routers.registry-github-https.entrypoints=websecure
      - traefik.http.routers.registry-github-https.tls=true
      - traefik.http.routers.registry-github-https.tls.certresolver=letsencryptresolver
      - traefik.http.services.registry-github.loadbalancer.server.port=5000
    environment:
      - TZ=Europe/Amsterdam
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_PROXY_REMOTEURL=https://ghcr.io
    restart: no
    networks:
      - traefik-net
      
  registry-linuxserver:
    image: registry:2.8.2
    container_name: registry-linuxserver
    hostname: registry-linuxserver
    volumes:
      - /mnt/tank/container_data/registry_images:/var/lib/registry
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry-linuxserver-https.rule=Host(`registry-linuxserver.home.mydomain.com`)
      - traefik.http.routers.registry-linuxserver-https.entrypoints=websecure
      - traefik.http.routers.registry-linuxserver-https.tls=true
      - traefik.http.routers.registry-linuxserver-https.tls.certresolver=letsencryptresolver
      - traefik.http.services.registry-linuxserver.loadbalancer.server.port=5000
    environment:
      - TZ=Europe/Amsterdam
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_PROXY_REMOTEURL=https://lscr.io
    restart: no
    networks:
      - traefik-net
      
networks:
  traefik-net:
    external: true
```
