### ISSUE TITLE
how to perform trigger?

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#51]
Install and have it run... Now how do I set up and put some triggers? I don't see any UI to do that? Some help? Also, its seems that all my docker container is only shown as latest instead its tag version? Any idea?

**Comment by fmartinou** [comment]
Hi,

All has to be configured by environment variables (including triggers).
It's explained in the documentation ([example for Smtp trigger](https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/smtp/))

Tuning versions to track can be achieved by adding Docker labels (using regex) on the containers to track.
It's explained in the documentation ([supported docker labels](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/docker/?id=supported-labels))

**Comment by ranrinc** [comment]
OK need to try, still unsure but I think I get your point. On the other hand, I will need to replace all my docker and add WUD tag on it + adding the correct tag right? I guess will have to do it on weekend. Since all my docker scattered on my home lab hahahahahahaha

**Comment by fmartinou** [comment]
Yes.

Below a sample of my docker-compose.yml as a starting point.

```yaml
version: '3'

services:

    # Bitwarden
    bitwarden:
        image: vaultwarden/server:1.22.1-alpine
        container_name: bitwarden
        labels:
            - 'wud.tag.include=^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-alpine$$'

    # Calibre
    calibre:
        image: linuxserver/calibre-web:0.6.12-ls125
        container_name: calibre
        labels:
            - 'wud.tag.include=^[0-9]\d*\.[0-9]\d*\.[0-9]\d*-ls[0-9]\d*$$'
            
    # Duplicati
    duplicati:
        image: linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls104
        container_name: duplicati
        labels:
            - 'wud.tag.include=^v[0-9]\d*\.[0-9]\d*\.[0-9]\d*\.[0-9]\d*-[0-9]\d*\.[0-9]\d*\.[0-9]\d*\.[0-9]\d*.*$$'
            
    # Homeassistant
    homeassistant:
        image: homeassistant/home-assistant:2021.7.1
        container_name: homeassistant
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Homeassistant_db
    homeassistant_db:
        image: mariadb:10.6.2
        container_name: homeassistant_db
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Mosquitto
    mosquitto:
        image: eclipse-mosquitto:2.0.11
        container_name: mosquitto
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Nextcloud
    nextcloud:
        image: nextcloud:22.0.0
        container_name: nextcloud
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Nextcloud_db
    nextcloud_db:
        image: mariadb:10.5.9
        container_name: nextcloud_db
        command: --max-connections=800
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Photoprism
    photoprism:
        image: photoprism/photoprism:20210523
        container_name: photoprism
        labels:
            - 'wud.tag.include=^([0-9]{8})$$'           

    # Photoprism_db
    photoprism_db:
        image: mariadb:10.6.2
        container_name: photoprism_db
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Pihole
    pihole:
        image: pihole/pihole:v5.8
        container_name: pihole
        labels:
            - 'wud.tag.include=^v(0|[1-9]\d*)\.(0|[1-9]\d*)$$'

    # Plex
    plex:
        image: linuxserver/plex:1.23.3.4707-ebb5fe9f3-ls60
        container_name: plex
        labels:
            - 'wud.tag.include=^[0-9]\d*\.[0-9]\d*\.[0-9]\d*\.[0-9]\d*-[0-9a-z]*-ls[0-9]\d*$$'

    # Portainer
    portainer:
        image: portainer/portainer-ce:2.6.1-alpine
        container_name: portainer
        restart: always
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)-alpine$$'           

    # Pyload
    pyload:
        image: writl/pyload:latest
        container_name: pyload
        labels:
            - 'wud.tag.include=latest'
            - 'wud.watch.digest=true'

    # Traefik
    traefik:
        image: traefik:2.4.9
        container_name: traefik
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

    # Whatsupdocker
    whatsupdocker:
        image: fmartinou/whats-up-docker:5.1.0
        container_name: whatsupdocker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/services/whatsupdocker/store:/store
        environment:
            - WUD_TRIGGER_MQTT_LOCAL_URL=mqtt://mosquitto:1883
            - WUD_TRIGGER_MQTT_LOCAL_HASS_ENABLED=true
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'

```

**Comment by ranrinc** [comment]
Thank you soo much for the help.. I got it..

**Comment by ranrinc** [comment]
BTW quick question for those of us who run Supervised version.. then we won't have the luxury to change the tag then?

**Comment by fmartinou** [comment]
I'm not using Supervisor (for home-assistant I guess?) so I'm not able to answer.
Apparently, you should run your containers "directly" ([see here](https://community.home-assistant.io/t/whats-up-docker-how-to-keep-your-containers-up-to-date/168315/47?u=fmartinou)) and not through Supervisor.

If your question is related to Home-Assistant, feel free to [ask on the forum](https://community.home-assistant.io/t/whats-up-docker-how-to-keep-your-containers-up-to-date/168315) for better chance to get answers ;)

**Comment by ranrinc** [comment]
Got problem trying to get remote hosts.

Unsure what or why since portainer and HA able to get all the informations using the same TLS certs

```
version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:5.1.0
    container_name: whatsupdocker
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/certs/ca.pem:/certs/ca.pem
      - /docker/certs/cert.pem:/certs/cert.pem
      - /docker/certs/key.pem:/certs/key.pem
      - /docker/wud/store:/store
    environment:
      - WUD_WATCHER_hass_HOST=192.168.8.80
      - WUD_WATCHER_hass_PORT=2376
      - WUD_WATCHER_hass_CAFILE=/certs/ca.pem
      - WUD_WATCHER_hass_CERTFILE=/certs/cert.pem
      - WUD_WATCHER_hass_KEYFILE=/certs/key.pem
      - WUD_WATCHER_hass_WATCHALL=true
    labels:
      - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'
```

error logs from portainer
```
[2021-07-16T14:39:38.584Z]  WARN: whats-up-docker/7 on 88d838cb7986:

    Error when trying to get the containers list to watch (write EPROTO 139790109231984:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 48

    )
```
