### ISSUE TITLE
Incorrect Newest Tag

### ISSUE THREAD

**Issue by jeremywillans** [fmartinou/whats-up-docker#69]
WUD is detecting the incorrect tag as the newest

Image: https://github.com/goauthentik/authentik/pkgs/container/server
I do not have digest enabled for this container.

WUD:
![What_s_up_Docker_](https://user-images.githubusercontent.com/31495062/134437104-a2306d59-78ae-4e2c-89ce-06ec3ab32547.png)

GHCR:
![Package_server](https://user-images.githubusercontent.com/31495062/134437156-b4a55574-4386-47ce-93b2-1967f1dbc432.png)

**Comment by fmartinou** [comment]
I'll take a look.

In the mean time, as a quick fix, you can exclude release candidates from potential updates [by adding a simple label on your authentik container](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=include-only-3-digits-semver-tags):

```
version: '3'

services:

  authentikdev:
    image: ghcr.io/goauthentik/server:2021.9.1
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
    ...
```

By the way, thank you for making me discover the [Authentik](https://goauthentik.io/) project.
It looks very promising! (I'm personally using [Authelia](https://www.authelia.com/) right now)
