### ISSUE TITLE
HA addon showing wrong tag

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#71]
In HA + Supervisor everything when well accept for one single addon (ESPHome) which is showing totally different tags. I believe it using github repo instead of dockerhub. Unsure how to fix this one.

![Screen Shot 2021-09-24 at 1 11 16 PM](https://user-images.githubusercontent.com/15801696/134627258-28096d7a-8c7c-46be-b6fe-74192037a7e8.png)

**UPDATE:**
I double-check on docker hub it should say we are on the right version since it's the latest. This is definitely a bug

**Comment by fmartinou** [comment]
Hi,

It's because `13696b1` (that should be a build number or something like that) is considered as a valid semver and semantically higher than `2021.9.1`.

To deal with that kind of situation, you just need to tell wud which tag pattern you're expecting.
E.g.

```
version: '3'

services:

  esphome:
    image: esphome/sesphome:2021.9.1
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
    ...
```
