### ISSUE TITLE
WUD fails to check for new image versions if a tag that contains numbers is used

### ISSUE THREAD

**Issue by oyxnaut** [fmartinou/whats-up-docker#8]
It seems the logic to decide if a tag is semver, or not isn't working properly.
I've tested the following image:tag combinations, and they all resulted in a TypeError in semver.js:
- traefik:2.2
- traefik:v2.2
- picodon@sha256:b50cb55e6800df703f31b9a312d018558fc2286f829510f7da3de44a40aa74b6
- mongo: 3
```json
{
  "name":"whats-up-doc",
  "hostname":"8ca68aea0e4b",
  "pid":1,
  "level":20,
  "err": {
    "message":"Invalid Version: v2.2",
    "name":"TypeError",
    "stack":"TypeError: Invalid Version: v2.2\n
      at new SemVer (/home/node/app/node_modules/semver/classes/semver.js:41:13)\n
      at compare (/home/node/app/node_modules/semver/functions/compare.js:3:32)\n
      at Object.gt (/home/node/app/node_modules/semver/functions/gt.js:2:29)\n
      at isNewerTag (/home/node/app/watcher/providers/docker/Docker.js:46:23)\n
      at /home/node/app/watcher/providers/docker/Docker.js:153:59\n
      at Array.find (<anonymous>)\n
      at Docker.findNewVersion (/home/node/app/watcher/providers/docker/Docker.js:153:45)\n
      at processTicksAndRejections (internal/process/task_queues.js:97:5)\n
      at async Docker.processImage (/home/node/app/watcher/providers/docker/Docker.js:106:22)\n
      at async Promise.all (index 0)"
  },
  "msg":"Invalid Version: v2.2",
  "time":"2020-07-16T10:40:07.588Z",
  "v":0
}
```
(Linebreaks added by me for readability)

I tried fixing the regex in the docker-parse-image dependency, but that only solved the issue for i.e. `traefik:2.2.0@sha256:b50cb55e6800df703f31b9a312d018558fc2286f829510f7da3de44a40aa74b6`

```diff
--- node_modules/docker-parse-image/index.js    2020-07-15 15:08:41.673688190 +0200                                                                      
+++ node_modules/docker-parse-image/index.js    2020-07-15 15:09:32.813281156 +0200
@@ -1,5 +1,5 @@
 module.exports = function(image) {
-  var match = image.match(/^(?:([^\/]+)\/)?(?:([^\/]+)\/)?([^@:\/]+)(?:[@:](.+))?$/)
+  var match = image.match(/^(?:([^\/]+)\/)?(?:([^\/]+)\/)?([^@:\/]+)(?:[@:]([^@]+))?(?:@(.+))?$/)
   if (!match) return null
 
   var registry = match[1]
```

I'm not sure if this is an issue with WUD, or if I should open it upstream with https://github.com/mafintosh/docker-parse-image

**Comment by fmartinou** [comment]
Hi,

First of all, thank you for your interest for this project!

To have the semver detection working properly, you often need to define some regex to include/exclude/sanitize Docker tags into comprehensible semver versions.

You can do it using Docker labels on the Docker Container to watch.

[See examples here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/docker?id=include-only-3-digits-semver-tags).

For example, to let WUD track Traefik updates (`2.2.5`, `2.2.6`...), a typical Docker Compose would look like:
(notice the Docker label meaning that we only want to watch 3 digits semver tags)
```
version: '3'

services:

    traefik:
        image: traefik:2.2.1
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'
```
Can you please retest with `wud.tag.include` and/or `wud.tag.exclude` labels?

If you still encounter issues, send me your full configuration.

**Comment by oyxnaut** [comment]
Thank you for the clarification w.r.t. the need to specify a regex. Unfortunately, this didn't solve the type error.
As you can see, all I did was change the image version to 2.1, and adjusted the regex accordingly.
```
version: '3'                                                                                                                                             

services:

    traefik:
        image: traefik:2.1
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - 'wud.tag.include=^([0-9]\d*).([0-9]\d*)$$'
```
However, using `image: traeffik:v2.1.1` with `wud-tag.include=^v([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$` works as expected.
