### ISSUE TITLE
Digest watch

### ISSUE THREAD

**Issue by elchanly** [fmartinou/whats-up-docker#95]
Why WUD_WATCHER_{watcher_name}_WATCHDIGEST is deprecated? 
I find it useful: I want to get rid of digest updates when i put     "  - WUD_TRIGGER_MQTT_MOSQUITTO_THRESHOLD=major". Now it displays also digest ones. 
IMHO to have it disabled as default and enable it only per container with the label would be more useful (or having the variable back, the best option)
Thanks for your work, this is a nice way to have docker updated!!

**Comment by fmartinou** [comment]
Hi,

First of all, thank you for your support!

> Why WUD_WATCHER_{watcher_name}_WATCHDIGEST is deprecated?

The variable is deprecated **at the global watcher level** but the feature of enabling/disabling digest watching is not removed.

Let me explain.

Watching digests is only useful when dealing with non semver image tags.
So by default, WUD per container:
- will track digests when the tag is not a semver
- won't track digests when the tag is a semver

<img width="600" src="https://user-images.githubusercontent.com/16061231/148681558-e44d7f41-6bc9-4cfd-ba93-e2f881a05d35.png">

If exceptionally, you want a different behavior for a specific container, you can still enforce [using a label on the container itself](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels).

Example:

```yaml
version: '3'

services:

  mariadb_semver:
    image: mariadb:10
    labels:
      - wud.watch.digest=true # exceptionally enable tracking digests on this container

  mariadb_non_semver:
    image: mariadb:latest
    labels:
      - wud.watch.digest=false# exceptionally disable tracking digests on this container
```

Regarding your situation, I'm quite unsure; is the version of mosquitto you run a semver or a non semver tag?
(because `WUD_TRIGGER_MQTT_MOSQUITTO_THRESHOLD=major` will only work with semver tags)
